### ISSUE TITLE
`NullReferenceException` when fertilizing vines

### ISSUE THREAD

**Issue by Battousai124** [nbusseneau/InstantFertilizer#1]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
InstantFertilizer.Patches.PickablePatches.PickableResetFertilizedWith (Pickable __instance, System.Boolean picked) (at <83ac3b53c7e04527b2f4d7151b55961a>:0)
(wrapper dynamic-method) Pickable.DMD<Pickable::SetPicked>(Pickable,bool)
Vine.CheckBerryBlocker () (at <79989041713a40fba2973f1624473248>:0)
Vine.Awake () (at <79989041713a40fba2973f1624473248>:0)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
Vine:DMD<Vine::Grow>(Vine, Vector3, Vector3, VineType, VineState, VineState)
Vine:CheckGrow(Vector3, VineType, VineState, VineState, VineState)
Vine:CheckGrowChance(Vector3, VineType, VineState, VineState, VineState)
Vine:UpdateGrow()

It's all I got.

**Comment by nbusseneau** [comment]
Thanks for the report, indeed I can reproduce the bug. I haven't reached Ashlands yet so I didn't know about the vines, will see what I can do.

**Comment by Battousai124** [comment]
No problem, take a look at the wiki, the vines differ greatly from the rest of the plantables.

**Comment by nbusseneau** [comment]
This should be fixed by 08c5bdc06485e8f00db58f18212958c7549d4e8c, released in [0.3.0](https://github.com/nbusseneau/InstantFertilizer/releases/tag/0.3.0).
